# Site settings
title: Geoinquietos
#email: xurxosanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este sitio muestra los diferentes grupos de geoinquietos y cómo contactar
  con ellos.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://test.geoinquietos.org" # the base hostname & protocol for your site

#twitter_username: geoinquietos_es
#github_username:  jsanz

# Build settings
markdown: kramdown
highlighter: pygments

# Collections
collections:
  groups:
    output: true
    permalink: /groups/:path/
  contacts:
    output: true
    permalink: /contacts/:path/

defaults:
  - scope:
      path: ""
      type: groups
    values:
      layout: group
  - scope:
      path: ""
      type: contacts
    values:
      layout: contact

cartodb:
  viz: https://team.cartodb.com/u/jsanz/api/v2/viz/3b8c1192-bd31-11e5-88e5-0ea31932ec1d/viz.json
  center:
    lat: 5
    lon: -44
  zoom: 2
  group_zoom: 7
  sql: "SELECT *, replace(_group,'Geoinquietos ','') as label FROM jsanz.groups"
