# Site settings
title: Geoinquietos
#email: xurxosanz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este sitio muestra los diferentes grupos de geoinquietos y cómo contactar
  con ellos.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geoinquietos.org" # the base hostname & protocol for your site

#twitter_username: geoinquietos_es
#github_username:  jsanz

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  groups:
    output: true
    permalink: /groups/:path/
  contacts:
    output: true
    permalink: /contacts/:path/

defaults:
  - scope:
      path: ""
      type: groups
    values:
      layout: group
  - scope:
      path: ""
      type: contacts
    values:
      layout: contact
